Update User Guide to be Projact based
AY2021S1-CS2103T-T17-4/tp pull request #35
Opened 2020-09-29 12:16 UTC by siqiang-ng

2020-09-29 15:40 UTC, JoeyToh requested changes

2020-09-29 15:40 UTC, JoeyToh commented on docs/UserGuide.md
> +Projact application consists of an address list, which stores the contacts of the other computing students, and a tag list, which stores the tags of the modules that the current user is taking in thi
1. "Address list" sounds a bit funny to me haha maybe contact list or phone book? Or keep it as address book? (but I'm not sure if this will fail the thingy when the script detects it).
2. I think we need to write in present tense: "The user **can** assign...."

2020-09-29 15:40 UTC, JoeyToh commented on docs/UserGuide.md
> +1. Download the latest `projact.jar` from [here](https://github.com/se-edu/addressbook-level3/releases).
Maybe we can just remove the link to the jar file for now, in case the script detects the link to AB3

2020-09-29 15:40 UTC, JoeyToh commented on docs/UserGuide.md
> +   * **`clear`** : Deletes all contacts in the address list.
Same comment as the introduction part. Perhaps address book/contact list/phonebook instead of address list? (Similarly for all other appearances of the word "address list")

2020-09-29 15:41 UTC, siqiang-ng commented on docs/UserGuide.md
> +Projact application consists of an address list, which stores the contacts of the other computing students, and a tag list, which stores the tags of the modules that the current user is taking in thi
oh wait haha i think i should change to contact list since the other parts I use contact list actually.

2020-09-29 15:42 UTC, siqiang-ng commented on docs/UserGuide.md
> +Projact application consists of an address list, which stores the contacts of the other computing students, and a tag list, which stores the tags of the modules that the current user is taking in thi
ok about the present tense, will take note

2020-09-29 15:46 UTC, siqiang-ng commented on docs/UserGuide.md
> +1. Download the latest `projact.jar` from [here](https://github.com/se-edu/addressbook-level3/releases).
ok done!

2020-09-29 15:46 UTC, siqiang-ng commented on docs/UserGuide.md
> +   * **`clear`** : Deletes all contacts in the address list.
done as well!

2020-09-30 04:49 UTC, JoeyToh approved these changes
Good to merge!

2020-09-30 04:50 UTC, merged